package com.iban.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * JPA Entity representing a validated IBAN stored in the database.
 *
 * ── What is JPA? ──
 * JPA (Jakarta Persistence API) is Java's standard ORM specification.
 * Hibernate is the most popular implementation — it maps Java objects to SQL tables.
 * ≈ Prisma (TS) or GORM (Go) — you define a class/struct and the ORM handles SQL.
 *
 * ── Why not a Record? ──
 * JPA entities MUST be mutable classes (not records) because Hibernate needs to:
 *   1. Create an empty instance via the no-arg constructor
 *   2. Set field values via setters/reflection after loading from DB
 * Records are immutable, so they can't be used as JPA entities.
 * Records are great for DTOs (request/response objects), entities need classes.
 *
 * ── Annotations explained ──
 * @Entity  — marks this class as a JPA entity (= a DB table row).
 *            ≈ Prisma's `model Iban { ... }` or GORM's `type Iban struct`
 * @Table   — specifies the DB table name. Without it, JPA uses the class name.
 *            ≈ Prisma's `@@map("ibans")` or GORM's `TableName()`
 */
@Entity
@Table(name = "ibans")
public class Iban {

    // @Id — marks this field as the primary key. ≈ `@id` in Prisma.
    // @GeneratedValue(IDENTITY) — the DB generates the ID (auto-increment).
    //   ≈ Prisma's `@default(autoincrement())` or `SERIAL` / `GENERATED BY DEFAULT AS IDENTITY` in SQL.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // @Column — maps this field to a specific column with constraints.
    //   nullable=false ≈ `NOT NULL` in SQL / Prisma's required field
    //   length=34       ≈ `VARCHAR(34)` in SQL / Prisma's `@db.VarChar(34)`
    //   If omitted, JPA infers column name from field name using camelCase→snake_case
    //   (e.g. bankName → bank_name). This is configured by Spring Boot's default
    //   naming strategy — no manual mapping needed.
    @Column(nullable = false, length = 34)
    private String iban;

    @Column(length = 255)
    private String bankName;

    @Column(length = 20)
    private String bankIdentifier;

    @Column(nullable = false)
    private boolean valid;

    @Column(nullable = false, length = 20)
    private String validationMethod;

    @Column(nullable = false)
    private Instant createdAt;

    // ── No-arg constructor ──
    // Required by JPA/Hibernate to create instances via reflection when loading
    // data from the database. "protected" prevents direct use outside the package.
    // ≈ In TS world, this is handled internally by Prisma/TypeORM.
    protected Iban() {
    }

    // ── Application constructor ──
    // Used in our code to create new entities before saving.
    public Iban(String iban, String bankName, String bankIdentifier, boolean valid, String validationMethod) {
        this.iban = iban;
        this.bankName = bankName;
        this.bankIdentifier = bankIdentifier;
        this.valid = valid;
        this.validationMethod = validationMethod;
        this.createdAt = Instant.now();
    }

    // ── Getters ──
    // Java convention: fields are private, accessed via getX() methods.
    // No Lombok used here — explicit getters for clarity.
    // ≈ In TS/Go you'd just access the field directly (entity.iban).
    // In Java, Jackson (JSON serializer) uses these getters to produce JSON output.

    public Long getId() {
        return id;
    }

    public String getIban() {
        return iban;
    }

    public String getBankName() {
        return bankName;
    }

    public String getBankIdentifier() {
        return bankIdentifier;
    }

    public boolean isValid() {
        return valid;
    }

    public String getValidationMethod() {
        return validationMethod;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
